from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class FindingSchema(BaseModel):
    """Granular code finding item conforming to unified schema."""
    id: str = Field(..., description="Unique finding ID e.g. find-001")
    category: str = Field(..., description="Finding category: 'bug' | 'security' | 'quality' | 'complexity'")
    severity: str = Field(..., description="Severity level: 'critical' | 'high' | 'medium' | 'low' | 'info'")
    title: str = Field(..., description="Short summary title of the issue")
    description: str = Field(..., description="Detailed explanation of the issue")
    line_start: int = Field(default=1, description="1-indexed starting line number")
    line_end: int = Field(default=1, description="1-indexed ending line number")
    code_snippet: str = Field(default="", description="Relevant code snippet")
    suggestion: str = Field(..., description="Recommended fix or refactoring advice")
    cwe_or_rule_id: Optional[str] = Field(default=None, description="CWE ID or standard rule reference (e.g. CWE-476)")


class AnalysisOutput(BaseModel):
    """Output generated by CodeAnalysisAgent."""
    overview: str = Field(..., description="High-level summary of what the code does and its structure")
    key_takeaways: List[str] = Field(default_factory=list, description="Key bullet points summarizing the code analysis")


class BugOutput(BaseModel):
    """Output generated by BugDetectionAgent."""
    findings: List[FindingSchema] = Field(default_factory=list, description="List of logic bugs and runtime issues detected")


class SecurityOutput(BaseModel):
    """Output generated by SecurityAgent."""
    findings: List[FindingSchema] = Field(default_factory=list, description="List of security vulnerabilities and CWE issues detected")


class QualityOutput(BaseModel):
    """Output generated by QualityReadabilityAgent."""
    findings: List[FindingSchema] = Field(default_factory=list, description="List of quality and readability issues")
    readability_score: float = Field(..., description="Readability score rating from 1.0 (poor) to 10.0 (excellent)")


class ComplexityOutput(BaseModel):
    """Output generated by ComplexityAgent."""
    findings: List[FindingSchema] = Field(default_factory=list, description="List of complexity bottlenecks")
    complexity_score: float = Field(..., description="Overall code complexity score from 1.0 (low complexity) to 10.0 (high complexity)")
    maintainability_index: str = Field(default="B", description="Maintainability grade: 'A' | 'B' | 'C' | 'D' | 'F'")
    cyclomatic_complexity_est: str = Field(default="Low", description="Cyclomatic complexity estimate e.g. 'Low' | 'Moderate' | 'High'")


class RefactoringOutput(BaseModel):
    """Output generated by RefactoringAgent."""
    refactored_code: str = Field(..., description="Complete, runnable refactored code block")
    diff_summary: str = Field(..., description="Plain-English explanation of changes made")


class SynthesisOutput(BaseModel):
    """Final unified synthesis output generated by SynthesizerAgent."""
    overview: str = Field(..., description="Executive summary overview")
    verdict: str = Field(..., description="Overall verdict: 'clean' | 'minor_issues' | 'major_issues' | 'critical_vulnerabilities'")
    key_takeaways: List[str] = Field(default_factory=list, description="Top key takeaways for developer")
    complexity_score: float = Field(default=5.0, description="Aggregate complexity score 1.0 - 10.0")
    readability_score: float = Field(default=8.0, description="Aggregate readability score 1.0 - 10.0")
    maintainability_index: str = Field(default="B", description="Maintainability grade")
    cyclomatic_complexity_est: str = Field(default="Low", description="Cyclomatic complexity rating")
    findings: List[FindingSchema] = Field(default_factory=list, description="Deduplicated list of findings across all categories")
